### ISSUE TITLE
Problems testing your demo

### ISSUE THREAD

**Issue by navido** [wolfgangimig/ddaddin#3]
Using Windows 10 and Outlook 2013 I receive the following error (noticed with both Firefox and Chrome):
![image](https://cloud.githubusercontent.com/assets/10881929/9959368/c02f89f6-5e13-11e5-8717-87d7ca837f5a.png)

**Comment by wolfgangimig** [comment]
You might have installed DDAddin 64bit and your Outlook is 32bit.
Or the 30 days demo period is expired.
Regards

**Comment by navido** [comment]
No I doublechecked it. I use Outlook 32 bit and installed DDAddin 32bit. And I just installed it. In the installer I left the key input empty.

**Comment by wolfgangimig** [comment]
Is DDAddin listed as an active Add-in in Outlook-Options? 
![image](https://cloud.githubusercontent.com/assets/3779094/9961346/4d8f7552-5e20-11e5-9022-938e71c6e27f.png)

If so, please configure logging as described [here](https://github.com/wolfgangimig/ddaddin/wiki/Configuration-Options#logging)

Then restart Outlook and perform a D&D.
Post the logfile here or send it per mail.

**Comment by navido** [comment]
No, it was not listed as an active Add-in. After I recently rebooted my system, it works like a charm!
