### ISSUE TITLE
DnD Issue

### ISSUE THREAD

**Issue by IvanIvanovItr** [wolfgangimig/ddaddin#8]
Hello, our DnD stopped working. We are not able to drag and drop files from Outlook 2010/2013 to Google Chrome. I start troubleshoot this issue and saw that there is no register for the license under this reg key : [HKEY_LOCAL_MACHINE\SOFTWARE\WILUTIONS\DnD to HTML5 Addin for Microsoft Outlook\License].
Dose it mean that if this key is missing we are using trail version?
We are using DDAddin License Key - UNLIMITED.
We are deploying DnD with SCCM and can you show us how we need to enter the license key information as a MSI property " PIDKEY= " just to confirm that we are entering license information correctly?

Hope soon to get in contact.

BR,
Ivan

**Comment by wolfgangimig** [comment]
Hi, 
the MSI property is called DDADDIN_LICENSE
Best regards,
Wolfgang

**Comment by IvanIvanovItr** [comment]
Hello,

thank you for your help. I think problem has been solved now.

BR,
Ivan
