### ISSUE TITLE
Copy/Paste issue 

### ISSUE THREAD

**Issue by b-worth** [wolfgangimig/ddaddin#9]
The following issue has been replicated over multiple Windows 7 machines using the ddaddin plugin for 
Outlook 2013
1. Open an Outlook message that has an attachment. Right-click and copy the attachment.
2. Open a new Outlook message. Right click and paste the attachment into the new email. The menu will pop up briefly and then disappear. The attachment cannot be pasted in this way.

However, CTRL-C/CTRL-V Works in addition to dragging and dropping as usual.

Thanks!

EDIT: Working on updating the machines soon. Thank you for the quick response!

**Comment by wolfgangimig** [comment]
Hi,
please make sure you have installed the latest version. This problem should have been solved in version 1.0.9, version comment:
- After mails were copied to clipboard, the context menu in Outlook's mail inspector window 
  appeared only for a short time. 

I cannot reproduce this effect with version 1.3.0 installed in Outlook 2016 on Windows 10.

Best regards,
Wolfgang
